# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dropbox\PycharmProjects\clock\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuForm(object):
    def setupUi(self, MenuForm):
        MenuForm.setObjectName("MenuForm")
        MenuForm.resize(326, 240)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MenuForm.setPalette(palette)
        self.info_b = QtWidgets.QCommandLinkButton(MenuForm)
        self.info_b.setGeometry(QtCore.QRect(0, 30, 171, 71))
        self.info_b.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.info_b.setTabletTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/.png/icons/togle_time.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/.png/icons/togle_time2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/.png/icons/togle_time.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/.png/icons/togle_time2.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.info_b.setIcon(icon)
        self.info_b.setIconSize(QtCore.QSize(160, 100))
        self.info_b.setObjectName("info_b")
        self.exit_Button = QtWidgets.QCommandLinkButton(MenuForm)
        self.exit_Button.setGeometry(QtCore.QRect(80, 130, 171, 71))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/.png/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_Button.setIcon(icon1)
        self.exit_Button.setIconSize(QtCore.QSize(160, 100))
        self.exit_Button.setObjectName("exit_Button")
        self.ap_button = QtWidgets.QCommandLinkButton(MenuForm)
        self.ap_button.setGeometry(QtCore.QRect(160, 30, 171, 71))
        self.ap_button.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/.png/icons/ap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/.png/icons/ap2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ap_button.setIcon(icon2)
        self.ap_button.setIconSize(QtCore.QSize(160, 100))
        self.ap_button.setObjectName("ap_button")

        self.retranslateUi(MenuForm)
        QtCore.QMetaObject.connectSlotsByName(MenuForm)

    def retranslateUi(self, MenuForm):
        _translate = QtCore.QCoreApplication.translate
        MenuForm.setWindowTitle(_translate("MenuForm", "Form"))
        self.info_b.setText(_translate("MenuForm", "Info"))
        self.exit_Button.setText(_translate("MenuForm", "Exit"))
        self.ap_button.setText(_translate("MenuForm", "CommandLinkButton"))


from data.icons.source import *
