# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Clock(object):
    def setupUi(self, Clock):
        Clock.setObjectName("Clock")
        Clock.resize(320, 240)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Clock.setPalette(palette)
        Clock.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        Clock.setAutoFillBackground(True)
        self.pushButton = QtWidgets.QPushButton(Clock)
        self.pushButton.setGeometry(QtCore.QRect(136, 190, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 149, 149))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setObjectName("pushButton")
        self.lcdNumber = QtWidgets.QLCDNumber(Clock)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 320, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setAutoFillBackground(True)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setNumDigits(5)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("value", 8230.0)
        self.lcdNumber.setProperty("intValue", 8230)
        self.lcdNumber.setObjectName("lcdNumber")
        self.temp_sign = QtWidgets.QLabel(Clock)
        self.temp_sign.setGeometry(QtCore.QRect(10, 150, 31, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.temp_sign.setFont(font)
        self.temp_sign.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.temp_sign.setMouseTracking(False)
        self.temp_sign.setAutoFillBackground(True)
        self.temp_sign.setMidLineWidth(2)
        self.temp_sign.setText("    t°")
        self.temp_sign.setTextFormat(QtCore.Qt.RichText)
        self.temp_sign.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp_sign.setObjectName("temp_sign")
        self.co_sign = QtWidgets.QLabel(Clock)
        self.co_sign.setGeometry(QtCore.QRect(140, 150, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.co_sign.setFont(font)
        self.co_sign.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.co_sign.setAutoFillBackground(True)
        self.co_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.co_sign.setObjectName("co_sign")
        self.Temp_value = QtWidgets.QLabel(Clock)
        self.Temp_value.setGeometry(QtCore.QRect(30, 180, 101, 61))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.Temp_value.setFont(font)
        self.Temp_value.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.Temp_value.setMouseTracking(False)
        self.Temp_value.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Temp_value.setAutoFillBackground(True)
        self.Temp_value.setMidLineWidth(4)
        self.Temp_value.setTextFormat(QtCore.Qt.RichText)
        self.Temp_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Temp_value.setObjectName("Temp_value")
        self.co2_sign = QtWidgets.QLabel(Clock)
        self.co2_sign.setGeometry(QtCore.QRect(167, 171, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.co2_sign.setFont(font)
        self.co2_sign.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.co2_sign.setAutoFillBackground(False)
        self.co2_sign.setAlignment(QtCore.Qt.AlignCenter)
        self.co2_sign.setObjectName("co2_sign")
        self.co2_value = QtWidgets.QLabel(Clock)
        self.co2_value.setGeometry(QtCore.QRect(190, 180, 121, 61))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.co2_value.setFont(font)
        self.co2_value.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.co2_value.setMouseTracking(False)
        self.co2_value.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.co2_value.setAutoFillBackground(False)
        self.co2_value.setMidLineWidth(2)
        self.co2_value.setTextFormat(QtCore.Qt.RichText)
        self.co2_value.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.co2_value.setObjectName("co2_value")

        self.retranslateUi(Clock)
        QtCore.QMetaObject.connectSlotsByName(Clock)

    def retranslateUi(self, Clock):
        _translate = QtCore.QCoreApplication.translate
        Clock.setWindowTitle(_translate("Clock", "Form"))
        self.pushButton.setText(_translate("Clock", "M"))
        self.co_sign.setText(_translate("Clock", "co"))
        self.co2_sign.setText(_translate("Clock", "2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Clock = QtWidgets.QWidget()
    ui = Ui_Clock()
    ui.setupUi(Clock)
    Clock.show()
    sys.exit(app.exec_())

